<?php
/**
 * Silk_Company extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category       Silk
 * @package        Silk_Company
 * @copyright      Copyright (c) 2015
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Company link widget template
 *
 * @category    Silk
 * @package     Silk_Company
 * @author      Ultimate Module Creator
 */
?>
<?php $_company = $this->getCurrentCompany();?>
<?php if ($_company) :?>
    <div class="company-widget-link">
        <a href="<?php echo $_company->getCompanyUrl()?>"><?php echo $_company->getName()?></a>
    </div>
<?php endif;?>
