<?php 
/**
 * Mageix LLC
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to Mageix LLC's  End User License Agreement
 * that is bundled with this package in the file LICENSE.pdf
 * It is also available through the world-wide-web at this URL:
 * http://ixcba.com/index.php/license-guide/
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to webmaster@mageix.com so we can send you a copy immediately.
 *
 * DISCLAIMER
 * 
 * Magento Mageix IXCBADV Module
 *
 * @category	Checkout & Payments, Customer Registration & Login
 * @package 	Mageix_Ixcbadv
 * @copyright   Copyright (c) 2014 -  Mageix LLC 
 * @author      Brian Graham
 * @license	    http://ixcba.com/index.php/license-guide/   End User License Agreement
 *
 *
 *
 * Magento Mageix IXCBA Module
 * 
 * @category   Checkout & Payments
 * @package	   Mageix_Ixcba
 * @copyright  Copyright (c) 2011 Mageix LLC
 * @author     Brian Graham
 * @license   http://mageix.com/index.php/license-guide/   End User License Agreement
 */

if(Mage::helper('ixcbadv')->isLoginEnabled()): ?>
<div class="col2-set">
    <div class="col-1"></div>
            <strong class="f-left" style="line-height: 32px;">&nbsp;&nbsp;&nbsp;&nbsp;<?php echo $this->__('OR'); ?> &nbsp; </strong>
            <div id="LoginWithAmazon"></div>
</div>

<script>


<?php

if (Mage::app()->getStore()->isCurrentlySecure()) {

	$checkouturl = Mage::getUrl('ixcbadv/login', array('_secure'=>true));
	$urlPath = Mage::getUrl('ixcbadv/inline/session', array('_secure'=>true));

 }else{
	$urlPath = Mage::getUrl('ixcbadv/inline/session', array('_secure'=>false));
	$checkouturl = Mage::getUrl('ixcbadv/login', array('_secure'=>false));

 }

 /*
  if (Mage::app()->getStore()->isCurrentlySecure()) {

	$checkouturl = Mage::getUrl('ixcbadv/inline', array('_secure'=>true));
	$urlPath = Mage::getUrl('ixcbadv/inline/session', array('_secure'=>true));

 }else{
	$urlPath = Mage::getUrl('ixcbadv/inline/session', array('_secure'=>false));
	$checkouturl = Mage::getUrl('ixcbadv/inline', array('_secure'=>false));
	

 */
 
$merchantId = Mage::helper('core')->decrypt(Mage::helper("ixcbadv")->getMerchantId());
$sizeval = Mage::getStoreConfig('ixcbadv/mageix_button/button_size_ixcbadv');
$colorval = Mage::getStoreConfig('ixcbadv/mageix_button/button_color_ixcbadv');
$buttonType = "LwA"; 
echo str_replace('replace', '$', $this->getApaButton("amazon_widget_top", "LoginWithAmazon" , "openframe_top", $urlPath, $buttonType, $checkouturl, $sizeval, $colorval));

?>
</script>

<?php  endif; ?>