<?php if(Mage::getStoreConfig('megamenu/general/enabled')): ?>	
	<?php $megaMenu = $this->getMegamenuItems(); ?>
	<?php if(count($megaMenu)>0 || Mage::getStoreConfig('megamenu/general/home')==1):?>
		<div class="nav-container">
			<div class="nav-inner">
				<div class="nav-inner-inner">
					<ul class="megamenu clearfix" id="megamenu">
						<?php if(Mage::getStoreConfig('megamenu/general/home')==1): ?>
							<li class="homepage level0 nav-0 level-top">
								<a class="level0" href="<?php echo $this->getBaseUrl() ?>">
									<span><?php echo Mage::getStoreConfig('megamenu/general/hometext') ?></span>
								</a>
							</li>
						<?php endif ?>
						<?php if(count($megaMenu)>0): ?>
							<?php $i=0; foreach($megaMenu as $item): $i++ ?>
								<li class="level0 nav-<?php echo $i ?> level-top <?php echo $this->getClass($item) ?>">
									<?php echo $this->getMenuHtml($item) ?>
								</li>
							<?php endforeach ?>
						<?php endif ?>
					</ul>
				</div>
			</div>
		</div>
	<?php endif ?>
<?php endif ?>

<script>
jQuery(document).ready(function(){
	
});
</script>
