<?php
/**
 * Mageix LLC
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to Mageix LLC's  End User License Agreement
 * that is bundled with this package in the file LICENSE.pdf
 * It is also available through the world-wide-web at this URL:
 * http://ixcba.com/index.php/license-guide/
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to webmaster@mageix.com so we can send you a copy immediately.
 *
 * DISCLAIMER
 * 
 * Magento Mageix IXCBADV Module
 *
 * @category	Checkout & Payments, Customer Registration & Login
 * @package 	Mageix_Ixcbadv
 * @copyright   Copyright (c) 2014 -  Mageix LLC 
 * @author      Brian Graham
 * @license	    http://ixcba.com/index.php/license-guide/   End User License Agreement
 *
 *
 *
 * Magento Mageix IXCBA Module
 * 
 * @category   Checkout & Payments
 * @package	   Mageix_Ixcba
 * @copyright  Copyright (c) 2011 Mageix LLC
 * @author     Brian Graham
 * @license   http://mageix.com/index.php/license-guide/   End User License Agreement
 */

?>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('ixcbadv/js/jquery-1.7.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('ixcbadv/js/amazon_widgets.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('ixcbadv/js/inlinecheckout.js'); ?>"></script>
<?php
$head = $this->helper('ixcbadv')->getAllConfigVars();

$getConfigVar = Mage::helper('ixcbadv')->getAllConfigVars();
$merchantId = Mage::helper('core')->decrypt(Mage::helper("ixcbadv")->getMerchantId());




if(isset($head['sandbox_mode']) && $head['sandbox_mode'] == 1) {
	if(isset($head['country']) && $head['country'] == 'UK') {
		echo "<script src='https://static-eu.payments-amazon.com/OffAmazonPayments/uk/sandbox/js/Widgets.js?sellerId=".$merchantId." '></script><script>jQuery.noConflict();</script>";
	} elseif(isset($head['country']) && $head['country'] == 'DE') {
		echo "<script src='https://static-eu.payments-amazon.com/OffAmazonPayments/de/sandbox/js/Widgets.js?sellerId=".$merchantId." '></script><script>jQuery.noConflict();</script>";
	} else { // Default US Urls
		echo "<script src='https://static-na.payments-amazon.com/OffAmazonPayments/us/sandbox/js/Widgets.js?sellerId=".$merchantId." '></script><script>jQuery.noConflict();</script>";
	}
}else{
	if(isset($head['country']) && $head['country'] == 'UK') {
		echo "<script src='https://static-eu.payments-amazon.com/OffAmazonPayments/uk/js/Widgets.js?sellerId=".$merchantId."'></script><script>jQuery.noConflict();</script>";
	} elseif(isset($head['country']) && $head['country'] == 'DE') {
		echo "<script src='https://static-eu.payments-amazon.com/OffAmazonPayments/de/js/Widgets.js?sellerId=".$merchantId."'></script><script>jQuery.noConflict();</script>";
	} else {
		echo "<script src='https://static-na.payments-amazon.com/OffAmazonPayments/us/js/Widgets.js?sellerId=".$merchantId."'></script><script>jQuery.noConflict();</script>";
	}
}
     
   
     
     
        $sizeval = Mage::getStoreConfig('ixcbadv/mageix_button/button_size_ixcbadv');
        $colorval = Mage::getStoreConfig('ixcbadv/mageix_button/button_color_ixcbadv');
     
     if($getConfigVar['active'] == 1) {
	if (Mage::app()->getStore()->isCurrentlySecure()) {
		$checkouturl = $this->getUrl('ixcbadv/inline', array('_secure'=>true));
		$urlPath = Mage::getUrl('ixcbadv/inline/session', array('_secure'=>true));
	}else{
		$checkouturl = $this->getUrl('ixcbadv/inline', array('_secure'=>false));
		$urlPath = Mage::getUrl('ixcbadv/inline/session', array('_secure'=>false));
	}
	
	$isLoginEnabled = Mage::helper("ixcbadv")->isLoginEnabled();
                
        if(Mage::helper('ixcbadv')->isLoginEnabled()){
                
        $scope = "profile payments:widget payments:shipping_address";
                
        }else {
                
        $scope = "payments:widget";
                
        }
        
?>
	<style> .paypal-or { margin: 5px 0 5px 50px;  } .amazon_payments { color:blue; margin: 5px; } #AmazonInlineWidgetPayment { display:inline; } </style>
	
	<div id="AmazonInlineWidgetPayment"></div>
	
	<script type="text/javascript">
		//<!--			
			function inlinecallbackpayment(){
				window.location = '<?php echo $checkouturl; ?>';
			}
			
			
			amazon_widget_payment = new AmazonWidgets ('<?php echo $merchantId; ?>');
			amazon_widget_payment.createInlineButton('AmazonInlineWidgetPayment', 'PwA', '<?php echo $sizeval; ?>', '<?php echo $colorval; ?>', '<?php echo $checkouturl; ?>', '<?php echo $scope; ?>');
			amazon_widget_payment.renderWidget(amazon_widget_payment.inlineButton,'AmazonInlineWidgetPayment');
		//-->
	</script>
<?php 
	}

?>