<?php
	$bannerCollection = $this->getBannerCollection();
	$i = 0;
?>
<?php $timeDelay = $this->getDelayTime() ?>
<?php $showdesc = $this->isShowDescription() ?>
<?php $listStyle = $this->getListStyle() ?>
<?php $imagewidth = $this->getImageWidth() ?>
<?php $imageheight = $this->getImageHeight() ?>
<?php if (!count($bannerCollection)): ?>
<?php elseif ($listStyle == '1'):?>
<div id="slider-1" class="slide-container">
	<script type="text/javascript" src="<?php echo $this->getJsUrl('magestore/bannerslider/banner1.js') ?>"></script>
	<link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('css/magestore/bannerslider/banner1.css');?>" media="all" />
	<div id="slide-images" class="slide-show" style="width:<?php echo $imagewidth;?>px; height:<?php echo $imageheight;?>px;">
		<div id="pettabs" class="indentmenu">
			<ul>
			<?php foreach($bannerCollection as $banner): $i++; ?>
				<li><a href="#" rel="tab<?php echo $i;?>" <?php if ($i == 1) { echo 'class="selected"'; }?>><?php echo $i;?></a></li>
			<?php endforeach; ?>
			</ul>
		</div>
		<div class="banner-content-style1"> 
			<?php $i = 0; foreach ($bannerCollection as $banner): $i++; ?>
			<div id="tab<?php echo $i;?>" class="tabcontent">
				<a href="<?php echo $banner['weblink'];?>">
				<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . $banner['filename']?>" title="<?php echo $banner['title']?>" alt="<?php echo $banner['title']?>" style="width:<?php echo $imagewidth;?>px; height:<?php echo $imageheight;?>px;"/>				
				<?php if ($showdesc == '1'):?>
				<div class="banner_content" style="width:<?php echo $imagewidth - 20?>px;"><p><?php echo $banner['content']; ?></p></div>
				<?php endif;?>
				</a>
			</div>
			<?php endforeach; ?>
		</div>
	</div>
	<script type="text/javascript">
		<?php echo 'var delay = ' . $timeDelay . ';'; ?>
		var mypets=new ddtabcontent("pettabs");
		mypets.setpersist(true);
		mypets.setselectedClassTarget("link");
		mypets.init(delay);
	</script>
</div>

<?php elseif ($listStyle == '2'):?>
<div id="slider-2" class="slide-container">
<!--<script type="text/javascript" src="<?php echo $this->getJsUrl('magestore/bannerslider/jquery-1.4.2.min.js') ?>"></script>-->
<link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('css/magestore/bannerslider/banner2.css');?>" media="all" />
<script type="text/javascript">
var $j = jQuery.noConflict(); 
$j(document).ready(function(){
	//Execute the slideShow
	slideShow();
});
function slideShow() {

	//Set the opacity of all images to 0
	$j('#gallery a').css({opacity: 0.0});
	
	//Get the first image and display it (set it to full opacity)
	$j('#gallery a:first').css({opacity: 1.0});
	
	//Set the caption background to semi-transparent
	$j('#gallery .caption').css({opacity: 0.7});

	//Resize the width of the caption according to the image width
	$j('#gallery .caption').css({width: $j('#gallery a').find('img').css('width')});
	<?php if ($showdesc == '1'):?>
	//Get the caption of the first image from REL attribute and display it
	$j('#gallery .content').html($j('#gallery a:first').find('img').attr('rel'))
	.animate({opacity: 0.7}, 400);
	<?php endif ?>
	
	//Call the gallery function to run the slideshow, 6000 = change to next image after 6 seconds
	setInterval('gallery()',<?php echo $timeDelay; ?>);
	
}

function gallery() {
	
	//if no IMGs have the show class, grab the first image
	var current = ($j('#gallery a.show')?  $j('#gallery a.show') : $j('#gallery a:first'));

	//Get next image, if it reached the end of the slideshow, rotate it back to the first image
	var next = ((current.next().length) ? ((current.next().hasClass('caption'))? $j('#gallery a:first') :current.next()) : $j('#gallery a:first'));	
	
	//Get next image caption
	var caption = next.find('img').attr('rel');	
	
	//Set the fade in effect for the next image, show class has higher z-index
	next.css({opacity: 0.0})
	.addClass('show')
	.animate({opacity: 1.0}, 1000);

	//Hide the current image
	current.animate({opacity: 0.0}, 1000)
	.removeClass('show');
	
	//Set the opacity to 0 and height to 1px
	$j('#gallery .caption').animate({opacity: 0.0}, { queue:false, duration:0 }).animate({height: '1px'}, { queue:true, duration:300 });	
	
	//Animate the caption, opacity to 0.7 and heigth to 100px, a slide up effect
	$j('#gallery .caption').animate({opacity: 0.7},100 ).animate({height: '100px'},500 );
	
	//Display the content
	$j('#gallery .content').html(caption);
	
	
}
</script>
	<div id="gallery" style="width:<?php echo $imagewidth;?>px; height:<?php echo $imageheight;?>px;">
		<?php foreach ($bannerCollection as $banner):?>
		<a href="<?php echo $banner['weblink'];?>" class="">
			<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . $banner['filename']?>" width="<?php echo $imagewidth;?>" height="<?php echo $imageheight;?>" title="<?php echo $banner['title']?>" alt="<?php echo $banner['title']?>" <?php if ($showdesc == '1'):?> rel="<h3><?php echo $banner['title']?></h3><?php echo $banner['content']; ?>"<?php endif;?> />
		</a>
		<?php endforeach; ?>
		<?php if ($showdesc == '1'):?>
		<div class="caption"><div class="content"></div></div>
		<?php endif ?>
	</div>
</div>

<?php elseif ($listStyle == '3'):?>
<div id="slider-3" class="slide-container">
<!--<script type="text/javascript" src="<?php echo $this->getJsUrl('magestore/bannerslider/jquery-1.4.2.min.js') ?>"></script>-->
<link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('css/magestore/bannerslider/banner3.css');?>" media="all" />
<script type="text/javascript">
var $j = jQuery.noConflict(); 
$j(document).ready(function(){
	$j('#games').coinslider({ hoverPause: false });
});

(function($j) {

	var params 		= new Array;
	var order		= new Array;
	var images		= new Array;
	var links		= new Array;
	var linksTarget = new Array;
	var titles		= new Array;
	var interval	= new Array;
	var imagePos	= new Array;
	var appInterval = new Array;	
	var squarePos	= new Array;	
	var reverse		= new Array;
	
	$j.fn.coinslider= $j.fn.CoinSlider = function(options){
		
		init = function(el){
				
			order[el.id] 		= new Array();	// order of square appereance
			images[el.id]		= new Array();
			links[el.id]		= new Array();
			linksTarget[el.id]	= new Array();
			titles[el.id]		= new Array();
			imagePos[el.id]		= 0;
			squarePos[el.id]	= 0;
			reverse[el.id]		= 1;						
				
			params[el.id] = $j.extend({}, $j.fn.coinslider.defaults, options);
						
			// create images, links and titles arrays
			$j.each($j('#'+el.id+' img'), function(i,item){
				images[el.id][i] 		= $j(item).attr('src');
				links[el.id][i] 		= $j(item).parent().is('a') ? $j(item).parent().attr('href') : '';
				linksTarget[el.id][i] 	= $j(item).parent().is('a') ? $j(item).parent().attr('target') : '';
				titles[el.id][i] 		= $j(item).next().is('span') ? $j(item).next().html() : '';
				$j(item).hide();
				$j(item).next().hide();
			});			
			

			// set panel
			$j(el).css({
				'background-image':'url('+images[el.id][0]+')',
				'width': params[el.id].width,
				'height': params[el.id].height,
				'position': 'relative',
				'background-position': 'top left'
			}).wrap("<div class='coin-slider' id='coin-slider-"+el.id+"' />");	
			
				
			// create title bar
			$j('#'+el.id).append("<div class='cs-title' id='cs-title-"+el.id+"' style='position: absolute; bottom:0; left: 0; z-index: 1000; width:<?php echo $imagewidth - 20;?>px'></div>");
						
			$j.setFields(el);
			
			if(params[el.id].navigation)
				$j.setNavigation(el);
			
			$j.transition(el,0);
			$j.transitionCall(el);
				
		}
		
		// squares positions
		$j.setFields = function(el){
			
			tWidth = sWidth = parseInt(params[el.id].width/params[el.id].spw);
			tHeight = sHeight = parseInt(params[el.id].height/params[el.id].sph);
			
			counter = sLeft = sTop = 0;
			tgapx = gapx = params[el.id].width - params[el.id].spw*sWidth;
			tgapy = gapy = params[el.id].height - params[el.id].sph*sHeight;
			
			for(i=1;i <= params[el.id].sph;i++){
				gapx = tgapx;
				
					if(gapy > 0){
						gapy--;
						sHeight = tHeight+1;
					} else {
						sHeight = tHeight;
					}
				
				for(j=1; j <= params[el.id].spw; j++){	

					if(gapx > 0){
						gapx--;
						sWidth = tWidth+1;
					} else {
						sWidth = tWidth;
					}

					order[el.id][counter] = i+''+j;
					counter++;
					
					if(params[el.id].links)
						$j('#'+el.id).append("<a href='"+links[el.id][0]+"' class='cs-"+el.id+"' id='cs-"+el.id+i+j+"' style='width:"+sWidth+"px; height:"+sHeight+"px; float: left; position: absolute;'></a>");
					else
						$j('#'+el.id).append("<div class='cs-"+el.id+"' id='cs-"+el.id+i+j+"' style='width:"+sWidth+"px; height:"+sHeight+"px; float: left; position: absolute;'></div>");
								
					// positioning squares
					$j("#cs-"+el.id+i+j).css({ 
						'background-position': -sLeft +'px '+(-sTop+'px'),
						'left' : sLeft ,
						'top': sTop
					});
				
					sLeft += sWidth;
				}

				sTop += sHeight;
				sLeft = 0;					
					
			}
			
			
			$j('.cs-'+el.id).mouseover(function(){
				$j('#cs-navigation-'+el.id).show();
			});
		
			$j('.cs-'+el.id).mouseout(function(){
				$j('#cs-navigation-'+el.id).hide();
			});	
			
			$j('#cs-title-'+el.id).mouseover(function(){
				$j('#cs-navigation-'+el.id).show();
			});
		
			$j('#cs-title-'+el.id).mouseout(function(){
				$j('#cs-navigation-'+el.id).hide();
			});	
			
			if(params[el.id].hoverPause){	
				$j('.cs-'+el.id).mouseover(function(){
					params[el.id].pause = true;
				});
			
				$j('.cs-'+el.id).mouseout(function(){
					params[el.id].pause = false;
				});	
				
				$j('#cs-title-'+el.id).mouseover(function(){
					params[el.id].pause = true;
				});
			
				$j('#cs-title-'+el.id).mouseout(function(){
					params[el.id].pause = false;
				});	
			}
					
			
		};
				
		
		$j.transitionCall = function(el){
		
			clearInterval(interval[el.id]);	
			delay = params[el.id].delay + params[el.id].spw*params[el.id].sph*params[el.id].sDelay;
			interval[el.id] = setInterval(function() { $j.transition(el)  }, delay);
			
		}
		
		// transitions
		$j.transition = function(el,direction){
			
			if(params[el.id].pause == true) return;
			
			$j.effect(el);
			
			squarePos[el.id] = 0;
			appInterval[el.id] = setInterval(function() { $j.appereance(el,order[el.id][squarePos[el.id]])  },params[el.id].sDelay);
					
			$j(el).css({ 'background-image': 'url('+images[el.id][imagePos[el.id]]+')' });
			
			if(typeof(direction) == "undefined")
				imagePos[el.id]++;
			else
				if(direction == 'prev')
					imagePos[el.id]--;
				else
					imagePos[el.id] = direction;
		
			if  (imagePos[el.id] == images[el.id].length) {
				imagePos[el.id] = 0;
			}
			
			if (imagePos[el.id] == -1){
				imagePos[el.id] = images[el.id].length-1;
			}
	
			$j('.cs-button-'+el.id).removeClass('cs-active');
			$j('#cs-button-'+el.id+"-"+(imagePos[el.id]+1)).addClass('cs-active');
			
			if(titles[el.id][imagePos[el.id]]){
				$j('#cs-title-'+el.id).css({ 'opacity' : 0 }).animate({ 'opacity' : params[el.id].opacity }, params[el.id].titleSpeed);
				$j('#cs-title-'+el.id).html(titles[el.id][imagePos[el.id]]);
			} else {
				$j('#cs-title-'+el.id).css('opacity',0);
			}				
				
		};
		
		$j.appereance = function(el,sid){

			$j('.cs-'+el.id).attr('href',links[el.id][imagePos[el.id]]).attr('target',linksTarget[el.id][imagePos[el.id]]);

			if (squarePos[el.id] == params[el.id].spw*params[el.id].sph) {
				clearInterval(appInterval[el.id]);
				return;
			}

			$j('#cs-'+el.id+sid).css({ opacity: 0, 'background-image': 'url('+images[el.id][imagePos[el.id]]+')' });
			$j('#cs-'+el.id+sid).animate({ opacity: 1 }, 300);
			squarePos[el.id]++;
			
		};
		
		// navigation
		$j.setNavigation = function(el){
			// create prev and next 
			$j(el).append("<div id='cs-navigation-"+el.id+"'></div>");
			$j('#cs-navigation-'+el.id).hide();
			$j('#cs-navigation-'+el.id).append("<a href='#' id='cs-prev-"+el.id+"' class='cs-prev'><span>prev</span></a>");
			$j('#cs-navigation-'+el.id).append("<a href='#' id='cs-next-"+el.id+"' class='cs-next'><span>next</span></a>");
			$j('#cs-prev-'+el.id).css({
				'position' 	: 'absolute',
				'top'		: params[el.id].height/2 - 15,
				'left'		: 0,
				'z-index' 	: 1001,
				'line-height': '30px'
				//'opacity'	: params[el.id].opacity
			}).click( function(e){
				e.preventDefault();
				$j.transition(el,'prev');
				$j.transitionCall(el);				
			}).mouseover( function(){ $j('#cs-navigation-'+el.id).show() });
				
			$j('#cs-next-'+el.id).css({
				'position' 	: 'absolute',
				'top'		: params[el.id].height/2 - 15,
				'right'		: 0,
				'z-index' 	: 1001,
				'line-height': '30px'
				//'opacity'	: params[el.id].opacity
			}).click( function(e){
				e.preventDefault();
				$j.transition(el);
				$j.transitionCall(el);
			}).mouseover( function(){ $j('#cs-navigation-'+el.id).show() });
		
			// image buttons
			//$j("<div id='cs-buttons-"+el.id+"' class='cs-buttons'></div>").appendTo($j('#coin-slider-'+el.id));

			
			for(k=1;k<images[el.id].length+1;k++){
				$j('#cs-buttons-'+el.id).append("<a href='#' class='cs-button-"+el.id+"' id='cs-button-"+el.id+"-"+k+"'>"+k+"</a>");
			}
			
			$j.each($j('.cs-button-'+el.id), function(i,item){
				$j(item).click( function(e){
					$j('.cs-button-'+el.id).removeClass('cs-active');
					$j(this).addClass('cs-active');
					e.preventDefault();
					$j.transition(el,i);
					$j.transitionCall(el);				
				})
			});	
			
			$j('#cs-navigation-'+el.id+' a').mouseout(function(){
				$j('#cs-navigation-'+el.id).hide();
				params[el.id].pause = false;
			});						

			$j("#cs-buttons-"+el.id).css({
				'left'			: '50%',
				'margin-left' 	: -images[el.id].length*15/2-5,
				'position'		: 'relative'
				
			});
			
				
		}




		// effects
		$j.effect = function(el){
			
			effA = ['random','swirl','rain','straight'];
			if(params[el.id].effect == '')
				eff = effA[Math.floor(Math.random()*(effA.length))];
			else
				eff = params[el.id].effect;

			order[el.id] = new Array();

			if(eff == 'random'){
				counter = 0;
				  for(i=1;i <= params[el.id].sph;i++){
				  	for(j=1; j <= params[el.id].spw; j++){	
				  		order[el.id][counter] = i+''+j;
						counter++;
				  	}
				  }	
				$j.random(order[el.id]);
			}
			
			if(eff == 'rain')	{
				$j.rain(el);
			}
			
			if(eff == 'swirl')
				$j.swirl(el);
				
			if(eff == 'straight')
				$j.straight(el);
				
			reverse[el.id] *= -1;
			if(reverse[el.id] > 0){
				order[el.id].reverse();
			}

		}

			
		// shuffle array function
		$j.random = function(arr) {
						
		  var i = arr.length;
		  if ( i == 0 ) return false;
		  while ( --i ) {
		     var j = Math.floor( Math.random() * ( i + 1 ) );
		     var tempi = arr[i];
		     var tempj = arr[j];
		     arr[i] = tempj;
		     arr[j] = tempi;
		   }
		}	
		
		//swirl effect by milos popovic
		$j.swirl = function(el){

			var n = params[el.id].sph;
			var m = params[el.id].spw;

			var x = 1;
			var y = 1;
			var going = 0;
			var num = 0;
			var c = 0;
			
			var dowhile = true;
						
			while(dowhile) {
				
				num = (going==0 || going==2) ? m : n;
				
				for (i=1;i<=num;i++){
					
					order[el.id][c] = x+''+y;
					c++;

					if(i!=num){
						switch(going){
							case 0 : y++; break;
							case 1 : x++; break;
							case 2 : y--; break;
							case 3 : x--; break;
						
						}
					}
				}
				
				going = (going+1)%4;

				switch(going){
					case 0 : m--; y++; break;
					case 1 : n--; x++; break;
					case 2 : m--; y--; break;
					case 3 : n--; x--; break;		
				}
				
				check = $j.max(n,m) - $j.min(n,m);			
				if(m<=check && n<=check)
					dowhile = false;
									
			}
		}

		// rain effect
		$j.rain = function(el){
			var n = params[el.id].sph;
			var m = params[el.id].spw;

			var c = 0;
			var to = to2 = from = 1;
			var dowhile = true;


			while(dowhile){
				
				for(i=from;i<=to;i++){
					order[el.id][c] = i+''+parseInt(to2-i+1);
					c++;
				}
				
				to2++;
				
				if(to < n && to2 < m && n<m){
					to++;	
				}
				
				if(to < n && n>=m){
					to++;	
				}
				
				if(to2 > m){
					from++;
				}
				
				if(from > to) dowhile= false;
				
			}			

		}

		// straight effect
		$j.straight = function(el){
			counter = 0;
			for(i=1;i <= params[el.id].sph;i++){
				for(j=1; j <= params[el.id].spw; j++){	
					order[el.id][counter] = i+''+j;
					counter++;
				}
				
			}
		}

		$j.min = function(n,m){
			if (n>m) return m;
			else return n;
		}
		
		$j.max = function(n,m){
			if (n<m) return m;
			else return n;
		}		
	
	this.each (
		function(){ init(this); }
	);
	

	};


// default values
$j.fn.coinslider.defaults = {	
	width: <?php echo $imagewidth;?>, // width of slider panel
	height: <?php echo $imageheight;?>, // height of slider panel
	spw: 7, // squares per width
	sph: 5, // squares per height
	delay:<?php echo $timeDelay; ?>, // delay between images in ms
	sDelay: 30, // delay beetwen squares in ms
	opacity: 0.7, // opacity of title and navigation
	titleSpeed: 500, // speed of title appereance in ms
	effect: '', // random, swirl, rain, straight
	navigation: true, // prev next and buttons
	links : true, // show images as links 
	hoverPause: true // pause on hover		
};	

})(jQuery);
</script>
	<div id="gamesHolder">
		<div class="coin-slider" id="coin-slider-games">
			<div style="width:<?php echo $imagewidth;?>px; height: <?php echo $imageheight;?>px; position: relative;" id="games">
				<?php foreach ($bannerCollection as $banner):?>
				<a href="<?php echo $banner['weblink'];?>">
					<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . $banner['filename']?>" title="<?php echo $banner['title']?>" alt="<?php echo $banner['title']?>" style="width:<?php echo $imagewidth;?>px; height:<?php echo $imageheight;?>px; display: none;"/>
					<?php if ($showdesc == '1'):?>
						<span style="display: none;">
							<b><?php echo $banner['title']?></b><br><?php echo $banner['content']; ?>
						</span>
					<?php endif;?>
				</a>
				<?php endforeach ?>
			</div>
		</div>
	</div>
</div>

<?php elseif ($listStyle == '4'):?>
<div id="slider-4" class="slide-container">
<!--<script type="text/javascript" src="<?php echo $this->getJsUrl('magestore/bannerslider/jquery-1.5.2.min.js') ?>"></script>-->
<script type="text/javascript" src="<?php echo $this->getJsUrl('magestore/bannerslider/jquery-easing-1.3.pack.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->getJsUrl('magestore/bannerslider/jquery-easing-compatibility.1.2.pack.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/jquery.flexslider-min.js') ?>"></script>
<link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('css/flexslider.css');?>" media="all" />
<script type="text/javascript">
	
	var $j = jQuery.noConflict(); 
	$j(document).ready(function(){
		$j('#thumbs').flexslider({
	        animation: "slide",
	        controlNav: false,
	        animationLoop: false,
	        slideshow: false,
	        itemWidth: 80,
	        itemMargin: 5,
	        asNavFor: '#slider',
	        prevText: "",
	        nextText: ""
	      });

	      $j('#slider').flexslider({
	        animation: "slide",
	        controlNav: false,
	        animationLoop: true,
	        slideshow: true,
	        sync: "#thumbs",
	        prevText: "",
	        nextText: ""
	        // start: function(slider){
	        //   $('body').removeClass('loading');
	        // }
	      });
	});
</script>
	
	<div id="slider" class="flexslider">
		<ul class="slides">
			<?php $i = 0; foreach ($bannerCollection as $banner): $i++; ?>
			<li>
			<!-- <div class="panel" title="Panel <?php echo $i;?>"> -->
				<div class="wrapper-content-slider4">
					<a href="<?php echo $banner['weblink'];?>">
					<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . $banner['filename']?>" title="<?php echo $banner['title']?>" alt="<?php echo $banner['title']?>" />
					<!-- <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . $banner['filename']?>" title="<?php echo $banner['title']?>" alt="<?php echo $banner['title']?>"/> -->
					</a>
					<?php if ($showdesc == '1'):?>
					<div class="photo-meta-data">
					<!-- <div class="photo-meta-data"> -->
						<b><?php echo $banner['title']?></b><br />
						<span><?php echo $banner['content']; ?></span>
					</div>
					<?php endif;?>
				</div>
			</li>
			<?php endforeach ?>
		</ul>
	</div>
	<div id="thumbs" class="flexslider">
		<ul class="slides">
			<?php $i = 0; foreach ($bannerCollection as $banner): $i++; ?>
			<li class="image-thumb"><img class="nav-thumb" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . $banner['filename']?>" title="<?php echo $banner['title']?>" alt="<?php echo $banner['title']?>" /></li>
			<?php endforeach ?>
		</ul>
	</div>
	
</div>

<?php elseif ($listStyle == '5'):?>
<div id="adPicM">
<ul class="slider">
	<?php $i = 0; foreach ($bannerCollection as $banner): $i++; ?>
	<li><a href="<?php echo $banner['weblink'];?>"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . $banner['filename']?>" title="<?php echo $banner['title']?>" alt="<?php echo $banner['title']?>" style="width:<?php echo $imagewidth;?>px; height:<?php echo $imageheight;?>px;"/></a><?php if ($showdesc == '1'):?><p><?php echo $banner['content']; ?></p><?php endif;?></li>
	<?php endforeach; ?>
</ul>
<ul class="num">
<?php for($k=1; $k<$i+1; $k++):?>
<li><?php echo $k;?></li>
<?php endfor;?>
</ul>
</div>


<?php elseif ($listStyle == ''):?>
	<?php echo ("Please Upload Banner Or Configuration"); ?>
<?php endif;?>
<div class="clear"></div>
