<?php
/**
* @author Amasty Team
* @copyright Amasty
* @package Amasty_Conf
*/
?>
<style>
em{
    color:red;
}

dt{
    font-weight: 400;
}
</style>
<?php
$_product    = $this->getProduct();
$_attributes = Mage::helper('core')->decorateArray($this->getAllowAttributes());

?>
<?php if ($_product->isSaleable() && count($_attributes) ||$_product->isconfigurable()):?>
    <dl>
    <?php foreach($_attributes as $_attribute): ?>

        <dt id="label-<?php echo $_attribute->getAttributeId() ?>-<?php echo $_product->getEntityId() ?>"><!-- label class="required"><em>*</em> <?php echo $_attribute->getLabel() ?></label --></dt>
        <dd<?php if ($_attribute->decoratedIsLast){?> class="last"<?php }?>>
            <div class="input-box" style="margin: 2px;">
                <select name="super_attribute[<?php echo $_attribute->getAttributeId() ?>]" id="attribute<?php echo $_attribute->getAttributeId() ?>-<?php echo $_product->getEntityId() ?>" class="required-entry super-attribute-select-<?php echo $_product->getEntityId() ?>">
                    <option><?php echo $this->__('Choose an Option...') ?></option>
                </select>
              </div>
              <div id="requared-attribute<?php echo $_attribute->getAttributeId() ?>-<?php echo $_product->getEntityId() ?>" style="color:red"></div>
        </dd>
    <?php endforeach; ?>
    </dl>
    <script type="text/javascript">
        var spConfig = new Product.Config(<?php echo $this->getJsonConfig() ?>);
        optionsPrice['<?php echo $_product->getId();?>'] = new Product.OptionsPrice(<?php echo $this->getPriceJsonConfig();?>);
    </script>
<?php endif;?>

<script type="text/javascript">
<!--
//Replace the image path
jQuery.noConflict();
(function($){
	$(".input-box .amconf-image").each(function(){
		var tmpImg = $(this).attr('src');
		var tmpArr = tmpImg.split("/");
		tmpArr[(tmpArr.length)-1] = ($(this).attr('title').toLocaleLowerCase()) + '_dot.png';
		$(this).attr('src',tmpArr.join('/'));
		$(this).width('8');
		$(this).height('8');
	});
})(jQuery);
//-->
</script>
