<?php
/**
* @author Amasty Team
* @copyright Amasty
* @package Amasty_Conf
*/
    $_product = $this->getProduct();
    $_helper = $this->helper('catalog/output');
    $imageWidth = (int)Mage::getStoreConfig('amconf/size/preview_width');
    $imageHeight = (int)Mage::getStoreConfig('amconf/size/preview_height');
    $smallImageSize = (int)Mage::getStoreConfig('amconf/size/thumb');
    $itemCount = (int)Mage::getStoreConfig('amconf/carousel/visible_items');
?>
<?php if ('true' == (string) Mage::getConfig()->getNode('modules/Amasty_Label/active')): ?>
                <div class="amlabel-div">
                <?php echo Mage::helper('amlabel')->getLabels($_product, 'product') ?>
 <?php endif; ?>
<?php if ($_product->getImage() != 'no_selection' && $_product->getImage()): ?>
<div class="product-image">
    <?php
       // $_img = '<img id="amasty_zoom" width="'. $imageWidth .'" height="'. $imageHeight .'"
       //  data-zoom-image="'.$this->helper('catalog/image')->init($_product, 'image').'" src="'.$this->helper('catalog/image')->init($_product, 'image')->resize($imageWidth, $imageHeight).'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" />';
        $_img = '<img id="amasty_zoom" data-zoom-image="'.$this->helper('catalog/image')->init($_product, 'image').'" src="'.$this->helper('catalog/image')->init($_product, 'image').'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" />';
		 echo $_helper->productAttribute($_product, $_img, 'image');
    ?>
</div>

<?php else: ?>
<div class="product-image">
    <?php
       $_img = '<img id="amasty_zoom" data-zoom-image="'.$this->helper('catalog/image')->init($_product, 'image').'" src="'.$this->helper('catalog/image')->init($_product, 'image')->backgroundColor(array(0,0,0))->resize($imageWidth, $imageHeight).'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" />';
       echo $_helper->productAttribute($_product, $_img, 'image');
    ?>
</div>

<?php endif; ?>
<?php if ('true' == (string)Mage::getConfig()->getNode('modules/Amasty_Label/active')): ?>
                </div>
            <?php endif; ?>

<?php if (count($this->getGalleryImages()) > 0): ?>
<div class="more-views">
    <h2><?php echo $this->__('More Views') ?></h2>
    <div style="position: relative;">
        <div id="amasty_gallery">
             <?php foreach ($this->getGalleryImages() as $_image): ?>
                <a class="fancybox" href="<?php echo Mage::getStoreConfig('amconf/lightbox/thumbnail_lignhtbox')?$this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile()):"#"; ?>" data-image="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile()); ?>" data-zoom-image="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile()); ?>"  >
                    <img src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->backgroundColor(array(0,0,0))->resize($smallImageSize); ?>" width="<?php echo $smallImageSize;?>" height="<?php echo $smallImageSize;?>" alt="<?php echo $this->htmlEscape($_image->getLabel()) ?>"  title="<?php echo $this->htmlEscape($_image->getLabel()) ?>"/>
                </a>
             <?php endforeach; ?>
             
        </div>
            <div id="prevGallery" style="display:<?php if (count($this->getGalleryImages()) > $itemCount && Mage::getStoreConfig('amconf/carousel/enable')): ?>block<?php else :?>none<?php endif;?>;top:<?php echo $smallImageSize/2 - 17;?>px" class="MagicScrollArrows MagicScrollArrowPrev"></div>
            <div id="nextGallery" style="display:<?php if (count($this->getGalleryImages()) > $itemCount && Mage::getStoreConfig('amconf/carousel/enable')): ?>block<?php else :?>none<?php endif;?>;top:<?php echo $smallImageSize/2 - 17;?>px" class="MagicScrollArrows MagicScrollArrowNext"></div>
        <?php if (count($this->getGalleryImages()) > $itemCount && Mage::getStoreConfig('amconf/carousel/enable')): ?>
             <?php if (Mage::getStoreConfig('amconf/carousel/pagination')): ?>
                <div id="ampagination" style="margin-top: 10px;"></div>
             <?php endif; ?>
        <?php endif; ?>
     </div>
</div>
<?php endif; ?>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/jquery.mobile.custom.min.js')?>"></script>
<script type="text/javascript" >
	jQuery.noConflict();
	var Macro = {};
	Macro.calculate = function(){
	    var currentWidth = 0;
	    var obj = <?php echo Mage::helper('amconf/zoom')->jsParam()?>;
	    if(jQuery(window).width()<=640){
	    	obj["general"]["zoom_enable"] = 0;
		    obj["general"]["lightbox_enable"] = 0;
		    obj['zoom'] = {};
	    	currentWidth = jQuery(window).width()*0.84;
	    }else if(jQuery(window).width()<=767){
	    	currentWidth = jQuery(window).width()*0.94;
		}else{
	    	currentWidth = jQuery(window).width()*0.58
	    }
	    //console.log(Math.floor((currentWidth-20)/71));
	    if(Math.floor((currentWidth-44)/jQuery("#amasty_gallery>a:first").outerWidth(true)) >= 7){
	    	obj["carousel"]["items"] = 7;
		}else{
	    	obj["carousel"]["items"] = Math.floor((currentWidth-44)/jQuery("#amasty_gallery>a:first").outerWidth(true)) ;
		}
		if(obj["carousel"]["items"]<jQuery("#amasty_gallery>a").length){
			jQuery("#prevGallery").show();
			jQuery("#nextGallery").show();
		}
	    AmZoomerObj = new AmZoomer(obj);
		//console.log(obj);
	   	AmZoomerObj.loadCarousel();
	}
	jQuery(function(){
		Macro.calculate();
		jQuery(window).on("orientationchange",function(event){
			//alert("方向是：" + event.orientation);
			setTimeout(Macro.calculate, 300);
		});
// 	   	jQuery(window).resize(function() {
// 	   		setTimeout(Macro.calculate, 300);
// 		   	//console.log(jQuery(window).width());
// 	   	});
	});

</script>
