<?php
/**
 * Create account form template
 *
 * @var $this Silk_B2bregister_Block_Form_Register
 * @see app/design/frontend/enterprise/default/template/customer/form/register.phtml
 */
?>
<div class="account-create">
    <div class="page-title">
        <h1><?php echo $this->__('Become a BenQ B2B Partner') ?></h1>
        <p><?php echo $this->__('Thank you for your interest in joining BenQB2B.com. Please provide your contact info in the form below so a BenQ representative can contact you.') ?></p>
    </div>
    <?php echo $this->getChildHtml('form_fields_before')?>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="form-validate" enctype="multipart/form-data">
        <div class="fieldset">
            <input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
            <input type="hidden" name="success_url" value="<?php echo $this->getSuccessUrl() ?>" />
            <input type="hidden" name="error_url" value="<?php echo $this->getErrorUrl() ?>" />
            <input type="hidden" name="is_b2b" value="1" />
            <h2 class="legend"><?php echo $this->__('Personal Information') ?></h2>
            <ul class="form-list">
                <li class="fields">
                <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getFormData())->setForceUseCustomerAttributes(true)->toHtml() ?>
                </li>
                <li>
                    <label for="company_name"><?php echo $this->__('Company Name') ?></label>
                    <div class="input-box">
                        <input type="text" name="company_name" id="company_name" value="<?php echo $this->escapeHtml($this->getFormData()->getCompanyName()) ?>" title="<?php echo $this->__('Company Name') ?>" class="input-text " />
                    </div>
                </li>
                 <li>
                    <label for="company_id" class="required"><em>*</em><?php echo $this->__('Company ID') ?></label>
                    <div class="input-box">
                        <input type="text" name="company_id" id="company_id" value="<?php echo $this->escapeHtml($this->getFormData()->getCompanyId()) ?>" title="<?php echo $this->__('Company ID') ?>" class="input-text required-entry" />
                    </div>
                </li>
                  <li>
                    <label for="phone_no"><?php echo $this->__('Phone Number') ?></label>
                    <div class="input-box">
                        <input type="text" name="phone_no" id="phone_no" value="<?php echo $this->escapeHtml($this->getFormData()->getPhoneNo()) ?>" title="<?php echo $this->__('Phone Number ') ?>" class="input-text validate-number" />
                    </div>
                </li>
                <li>
                    <label for="email_address" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
                    <div class="input-box">
                        <input type="text" name="email" id="email_address" value="<?php echo $this->escapeHtml($this->getFormData()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" class="input-text validate-email required-entry" />
                    </div>
                </li>
                <li>
                    <label for="open_credit" class="required"><em>*</em><?php echo $this->__('Open-Credit Amount') ?></label>
                    <div class="input-box">
                        <input type="text" name="open_credit" id="open_credit" value="<?php echo $this->escapeHtml($this->getFormData()->getOpenCredit()) ?>" title="<?php echo $this->__('Open-Credit Amount') ?>" class="input-text required-entry validate-price" />
                    </div>
                </li>
                <li>
                    <label for="message" ><?php echo $this->__('Tell Us About Your Business') ?></label>
                    <div class="input-box">
                        <textarea name="message" id="message"  class="input-text" title="<?php echo $this->__('message') ?>"><?php echo $this->escapeHtml($this->getFormData()->getMessage()) ?></textarea>
                    </div>
                </li>
                 <li>
                    <label for="attachment"><?php echo $this->__('Attachment') ?></label>
                    <div class="input-box">
                        <input type="file" name="attachment" id="attachment" value="<?php echo $this->escapeHtml($this->getFormData()->getAttachment()) ?>" title="<?php echo $this->__('Attachment') ?>" class="input-text validate-file" />
                    </div>
                </li>

            <?php $_dob = $this->getLayout()->createBlock('customer/widget_dob') ?>
            <?php if ($_dob->isEnabled()): ?>
                <li><?php echo $_dob->setDate($this->getFormData()->getDob())->toHtml() ?></li>
            <?php endif ?>
            <?php $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat') ?>
            <?php if ($_taxvat->isEnabled()): ?>
                <li><?php echo $_taxvat->setTaxvat($this->getFormData()->getTaxvat())->toHtml() ?></li>
            <?php endif ?>
            <?php $_gender = $this->getLayout()->createBlock('customer/widget_gender') ?>
            <?php if ($_gender->isEnabled()): ?>
                <li><?php echo $_gender->setGender($this->getFormData()->getGender())->toHtml() ?></li>
            <?php endif ?>
            <?php $customerAttributes = $this->getChild('customer_form_user_attributes');?>
            <?php if ($customerAttributes): ?>
                <?php $customerAttributes->setShowContainer(false);?>
                <?php $this->restoreSessionData($customerAttributes->getForm());?>
                <?php echo $customerAttributes->toHtml()?>
            <?php endif;?>
            </ul>
        </div>
        <div class="divider"></div>
    <?php if($this->getShowAddressFields()): ?>
        <div class="fieldset">
            <input type="hidden" name="create_address" value="1" />
            <h2 class="legend"><?php echo $this->__('Address Information') ?></h2>
            <ul class="form-list">
                <li class="fields">
                    <div class="field">
                        <label for="company"><?php echo $this->__('Company') ?></label>
                        <div class="input-box">
                            <input type="text" maxlength="30" name="company" id="company" value="<?php echo $this->escapeHtml($this->getFormData()->getCompany()) ?>" title="<?php echo $this->__('Company') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('company') ?>" />
                        </div>
                    </div>
                    <div class="field">
                        <label for="telephone" class="required"><em>*</em><?php echo $this->__('Telephone') ?></label>
                        <div class="input-box">
                            <input type="text" name="telephone" id="telephone" value="<?php echo $this->escapeHtml($this->getFormData()->getTelephone()) ?>" title="<?php echo $this->__('Telephone') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('telephone') ?>" />
                        </div>
                    </div>
                </li>
            <?php $_streetValidationClass = $this->helper('customer/address')->getAttributeValidationClass('street'); ?>
                <li class="wide">
                    <label for="street_1" class="required"><em>*</em><?php echo $this->__('Street Address') ?></label>
                    <div class="input-box">
                        <input type="text" name="street[]" value="<?php echo $this->escapeHtml($this->getFormData()->getStreet(0)) ?>" title="<?php echo $this->__('Street Address') ?>" id="street_1" class="input-text <?php echo $_streetValidationClass ?>" />
                    </div>
                </li>
            <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
            <?php for ($_i = 2, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++): ?>
                <li class="add-field">
                    <div class="input-box">
                        <input type="text" name="street[]" value="<?php echo $this->escapeHtml($this->getFormData()->getStreet($_i - 1)) ?>" title="<?php echo $this->__('Street Address %s', $_i) ?>" id="street_<?php echo $_i ?>" class="input-text <?php echo $_streetValidationClass ?>" />
                    </div>
                </li>
            <?php endfor; ?>
                <li class="fields">
                    <div class="field">
                        <label for="city" class="required"><em>*</em><?php echo $this->__('City') ?></label>
                        <div class="input-box">
                            <input type="text" name="city" value="<?php echo $this->escapeHtml($this->getFormData()->getCity()) ?>" title="<?php echo $this->__('City') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('city') ?>" id="city" />
                        </div>
                    </div>
                    <div class="field">
                        <label for="region_id" class="required"><em>*</em><?php echo $this->__('State/Province') ?></label>
                        <div class="input-box">
                            <select id="region_id" name="region_id" title="<?php echo $this->__('State/Province') ?>" class="validate-select" style="display:none;">
                                <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                            </select>
                            <script type="text/javascript">
                            //<![CDATA[
                                $('region_id').setAttribute('defaultValue',  "<?php echo $this->getFormData()->getRegionId() ?>");
                            //]]>
                            </script>
                            <input type="text" id="region" name="region" value="<?php echo $this->escapeHtml($this->getRegion()) ?>" title="<?php echo $this->__('State/Province') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('region') ?>" style="display:none;" />
                        </div>
                    </div>
                </li>
                <li class="fields">
                    <div class="field">
                        <label for="zip" class="required"><em>*</em><?php echo $this->__('Zip/Postal Code') ?></label>
                        <div class="input-box">
                            <input type="text" name="postcode" value="<?php echo $this->escapeHtml($this->getFormData()->getPostcode()) ?>" title="<?php echo $this->__('Zip/Postal Code') ?>" id="zip" class="input-text validate-zip-international <?php echo $this->helper('customer/address')->getAttributeValidationClass('postcode') ?>" />
                        </div>
                    </div>
                    <div class="field">
                        <label for="country" class="required"><em>*</em><?php echo $this->__('Country') ?></label>
                        <div class="input-box">
                            <?php echo $this->getCountryHtmlSelect() ?>
                        </div>
                    </div>
                </li>
                <?php $addressAttributes = $this->getChild('customer_form_address_user_attributes');?>
                <?php if ($addressAttributes): ?>
                    <?php $addressAttributes->setEntity($this->getAddress());?>
                    <?php $addressAttributes->setFieldIdFormat('address:%1$s')->setFieldNameFormat('address[%1$s]');?>
                    <?php $this->restoreSessionData($addressAttributes->getForm(), 'address');?>
                    <?php echo $addressAttributes->setShowContainer(false)->toHtml()?>
                <?php endif;?>
            </ul>
            <input type="hidden" name="default_billing" value="1" />
            <input type="hidden" name="default_shipping" value="1" />
        </div>
        <div class="divider"></div>
    <?php endif; ?>
        <div class="fieldset">
            <h2 class="legend"><?php echo $this->__('Login Information') ?></h2>
            <ul class="form-list">
                <li class="fields">
                    <div class="field">
                        <label for="password" class="required"><em>*</em><?php echo $this->__('Password') ?></label>
                        <div class="input-box">
                            <input type="password" name="password" id="password" title="<?php echo $this->__('Password') ?>" class="input-text required-entry validate-password" />
                        </div>
                    </div>
                    <div class="field">
                        <label for="confirmation" class="required"><em>*</em><?php echo $this->__('Confirm Password') ?></label>
                        <div class="input-box">
                            <input type="password" name="confirmation" title="<?php echo $this->__('Confirm Password') ?>" id="confirmation" class="input-text required-entry validate-cpassword" />
                        </div>
                    </div>
                    <div class="field">
                        <label for="is_agreed"><?php echo $this->__('I have read and agree to Privacy Policy') ?></label>
                        <div class="input-box">
                        <input type="checkbox" name="is_agreed" title="<?php echo $this->__('Agree To') ?>" value="1" id="is_agreed"<?php if($this->getFormData()->getisAgreed()): ?> checked="checked"<?php endif; ?> class="checkbox required-entry" />
                        </div>
                    </div>
                </li>
                <?php echo $this->getChildHtml('form.additional.info'); ?>
                <?php echo $this->getChildHtml('persistent.remember.me'); ?>
            </ul>
            <?php echo $this->getChildHtml('persistent.remember.me.tooltip'); ?>
        </div>
        <div class="buttons-set form-buttons">
            <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
            <button type="submit" class="button" title="<?php echo $this->__('Submit') ?>"><?php echo $this->__('Submit') ?></button>
        </div>
        <p class="required"><?php echo $this->__('* Required Fields') ?></p>
        <?php if (Mage::helper('checkout')->isContextCheckout()): ?>
            <input name="context" type="hidden" value="checkout" />
        <?php endif; ?>
    </form>
    <div id ="privacy-policy" style="display:none"><?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('privacy_policy')->toHtml(); ?></div>
    <script type="text/javascript">
    //<![CDATA[
       jQuery(document).ready(function(){
            function showAgreeContent(id){
              var html = document.getElementById(id);
              win = new Window({
                    className:'greylighting',
                    title:"<?php echo $this->__('Privacy Policy'); ?>",
                    windowClassName:'agree',
                    resizable:false,
                    width: 800,
                    height: 550,
                    minimizable:false,
                    maximizable:false,
                    showEffectOptions: {
                        duration: 0.4
                    },
                    hideEffectOptions:{
                        duration: 0.4
                    },
                    destroyOnClose: true,
                });
                win.setHTMLContent(html.innerHTML);
                win.setZIndex(300);
                win.showCenter(true);
            }
            jQuery('#is_agreed').click(function(){
                var trigger = jQuery(this).attr('checked');
                if(trigger=='checked') showAgreeContent('privacy-policy');
            })
       })

        var dataForm = new VarienForm('form-validate', true);
        <?php if($this->getShowAddressFields()): ?>
        new RegionUpdater('country', 'region', 'region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'zip');
        <?php endif; ?>

        Form.getElements('form-validate').each(function(element) {
            element.setAttribute('autocomplete', 'off');
        });
        function getFiletype(filename){
            var extStart  = filename.lastIndexOf(".")+1;
            return filename.substring(extStart,filename.length).toUpperCase();}
        Validation.add('validate-file','Please upload file : \'pdf\',\'docx\',\'png\',\'jpg\',\'xlsx\'.',function(file) {
            if(!file) return true;
            var fileext1 = getFiletype(file);
            var allowtype =  ["PDF","DOCX","PNG","JPG","XLSX"];
            if (jQuery.inArray(fileext1,allowtype) == -1){
                return false;
            }
            return true;
        });
        Validation.add('validate-price', 'Please enter a valid price number in this field.', function(v) {
                return Validation.get('IsEmpty').test(v)
                    || (!isNaN(parseNumber(v)) && /^\s*-?\d*(\.\d*)?\s*$/.test(v));
            });
    //]]>
    </script>
</div>
